
const images = {
APP_ICON: require('../assets/app_icon.png'),
GRADIENT_BG:require('../assets/gradient_bg.png'),
ONBOARD_BG: require('../assets/onboard_bg.png'),
SEARCH_ICON: require('../assets/search_icon.png'),
CROSS_ICON: require('../assets/cross_icon.png'),
VIDEO_BG: require('../assets/video_bg.png'),
ONBOARD_BG2: require('../assets/onboard_bg2.png'),
ONBOARD_BG3: require('../assets/onboard_bg3.png'),
DOCTOR_IMAGE: require('../assets/doctor.png'),
PLAY_ICON: require('../assets/play_icon.png'),
TEETH_ICON: require('../assets/teeth_icon.png'),
EYE_ICON: require('../assets/eye_icon.png'),
BODY_ICON: require('../assets/body_icon.png'),
HEART_ICON: require('../assets/heart_icon.png'),
Right_ARROW: require('../assets/right_arrow.png'),
HOME_ICON: require('../assets/home_icon.png'),
LIKE_ICON: require('../assets/like_icon.png'),
READ_ICON: require('../assets/read_icon.png'),
CHAT_ICON: require('../assets/chat_icon.png'),
UNRATED_ICON: require('../assets/unrated_icon.png'),
USER_ICON: require('../assets/user_icon.png'),
SELECTED_HOME: require('../assets/selected_Home.png'),
SELECTED_LIKE: require('../assets/selected_like.png'),
SELECTED_CHAT: require('../assets/selected_chat.png'),
USER: require('../assets/user.png'),
BACK_ICON: require('../assets/back_icon.png'),
PERSON: require('../assets/person.png'),
GOOGLE_ICON: require('../assets/goggle_icon.png'),
FACEBOOK_ICON: require('../assets/facebook_icon.png'),
};
export default images;
